on: [push]

env:
  VERSION: "1.0.${{ github.run_number }}"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com

      - name: Create a package called @${{ github.repository }}
        run: npm init --scope ${{ github.repository_owner }} -y